### ISSUE TITLE
Multiple async requests will override cookies on server side!

### ISSUE THREAD

**Issue by ChrisCinelli** [eXon/react-cookie#10]
Correct me if I am wrong:

You have this : https://github.com/eXon/react-cookie/blob/master/index.js#L3
So you have only one place where the cookie are stored on the server. 

If I call the `plugToRequest` and then I have a one or more async requests on server before the rendering, there is the chance that the request of another user will overwrite the cookies. so a `load` will read the cookie of another user.

In isomorphic environment, in order to fix this it is necessary either not to call  `plugToRequest` is a async context or the cookies need to be store in the context.

**Comment by eXon** [comment]
Even though renderToString is sync, I agree plugToRequest should be able to split the context of every request. I'll take a look at what I can do.

**Comment by eXon** [comment]
I'm not sure it is possible to know what the context is. If you use plugToRequest before your renderToString, you should be fine.

Otherwise, I'm not sure there is a way to know the context unless I add a React wrapper to your app.

**Comment by ChrisCinelli** [comment]
I modified here https://github.com/ChrisCinelli/react-cookie-async the `plugToRequest` to return an handle to the current request but you will have to always pass it to all the other methods.

**Comment by eXon** [comment]
I don't think we need to add this because renderToString is synchronous. Let me know if it causes any troubles.
