### ISSUE TITLE
ReferenceError: path is not defined

### ISSUE THREAD

**Issue by lemonCMS** [eXon/react-cookie#11]
When i try to remove an cookie, i get the following error
````
Object.remove
/var/www/qm_2016/webapp2/node_modules/react-cookie/index.js:61:15
````
I can see that you are trying to access a variable named "path" that is not defined within that function.

Kind Reagrds,
Raymond

**Comment by ChrisCinelli** [comment]
I was getting that too. It is fixed on master here: https://github.com/ChrisCinelli/react-cookie

**Comment by lemonCMS** [comment]
After looking at your fix, it is my believe that that whole line should be removed.

````opt```` is alway overridding with undefined because the variable ````path```` never exists.

**Comment by eXon** [comment]
I'll fix this asap

**Comment by eXon** [comment]
The reason for this line is to be retro-compatible with the second option being the path only.

**Comment by lemonCMS** [comment]
What i mean is that the second param in the function is called ````opt```` 

````javascript
function remove(name, opt) {
  delete _rawCookie[name];

  if (typeof document !== 'undefined') {
    if (typeof opt === 'undefined') {
      opt = {};
    } else if (typeof opt === 'string') {
      // Will be deprecated in future versions
      opt = { path: opt };
    }

    opt.expires = new Date(1970, 1, 1, 0, 0, 1);

    document.cookie = cookie.serialize(name, '', opt);
  }

  if (_res && _res.clearCookie) {
    var opt = path ? { path: path } : undefined;
    _res.clearCookie(name, opt);
  }
}
````

So the line 
````javascript
var opt = path ? { path: path } : undefined;
````

will always return undefined, right?

I would rewrite the funtion as follows
````javascript
function remove(name, opt) {
  delete _rawCookie[name];
    if (typeof opt === 'undefined') {
      opt = {};
    } else if (typeof opt === 'string') {
      // Will be deprecated in future versions
      opt = { path: opt };
    }

  if (typeof document !== 'undefined') {
    opt.expires = new Date(1970, 1, 1, 0, 0, 1);

    document.cookie = cookie.serialize(name, '', opt);
  }

  if (_res && _res.clearCookie) {
     _res.clearCookie(name, opt);
  }
}
````

But perhaps i am just missing something in that case nevermind.

**Comment by eXon** [comment]
I understand your problem, it will be fixed asap.

**Comment by eXon** [comment]
It has been fixed. Thanks for reporting!
