### ISSUE TITLE
fail to load httpOnly cookies "connect.sid"

### ISSUE THREAD

**Issue by ssmlee04** [eXon/react-cookie#13]
I can retrieve the cookie values in my react application except for one httpOnly cookie called "connect.sid". So I wonder if this is the problem?

**Comment by eXon** [comment]
Can you copy/paste your raw value of `document.cookie` here?

**Comment by ssmlee04** [comment]
document.cookie do not have connect.sid field. But from Chrome debug console connect.sid is in there and shows http only

**Comment by eXon** [comment]
It is because httpOnly means only the server has access to the cookie. You cannot have access client-side with javascript.

You can take a look at [httpOnly on Wikipedia](https://www.owasp.org/index.php/HttpOnly).

**Comment by ssmlee04** [comment]
I was using a boilerplate called isomorphic500 where both client and server share some states and it appears that we have access to req in both places.  So is this doable in this current project?

**Comment by eXon** [comment]
You can't use the cookie inside client-side code unless your cookie is not http. Here is how you can do it with express:

```javascript
app.use(express.session({
    secret: 'mySecret',
    cookie: { httpOnly: false }
}));
```
