### ISSUE TITLE
remove cookie when tab closes

### ISSUE THREAD

**Issue by andreasi** [eXon/react-cookie#14]
Is there a way to remove the cookie that was set via cookie.save() when the tab closes? Also how is it possible to set a session cookie. I set the cookie on the client side. I use this extension chrome-extension://iphcomljdfghbkdcfndaijbokpgddeno/editor.html to see my cookies and in the one that is set,  the session check is not there. 
Thanks

**Comment by eXon** [comment]
This is acting the same way any cookie would on your browser. By default, it is a session cookie unless you set an expiration date.
