### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by Ganasist** [eXon/react-cookie#15]
1) Is it possible to set / remove multiple cookies in one line? When I tried something like this it didn't work:
```
cookie.save('memberID', resp.member.id, 'memberName', resp.member.fullname)
```

2) How can I set secure: true and httpOnly: true? When I tried something like this it didn't appear to work:

```
cookie.save('memberName', resp.member.fullname, {secure: true, httpOnly: true})
```

**Comment by eXon** [comment]
1. You can't set multiple cookie at once. You have to set them one by one.
2. httpOnly cookies cannot be set with Javascript. By definition, only the server can touch them. This should do the trick:

```javascript
cookie.save('memberName', name, { path: '/', secure: true });
// ... 
```
