### ISSUE TITLE
multiple cookies with same key

### ISSUE THREAD

**Issue by jamesfzhang** [eXon/react-cookie#17]
I store my user's ID & auth token in cookies and send them with requests via headers. I save the ID & token upon successful login, delete the ID & token upon logout. After logging in & out several times, I inspected `document.cookie` and noticed that the same key value pairs (`__myapp:userID` and `__myapp:authenticationToken`) appear over and over again. It appears that `remove` isn't actually removing the cookie correctly. Furthermore, once the value for a cookie is saved, shouldn't subsequent calls to saving that cookie override the value?

```js
document.cookie

"__myapp:userID=2; __myapp:authenticationToken=AgXsUmhMRZYPLePhxcyc; userID=2; authenticationToken=NzMZ915j5bz2gbs99Hhm; __myapp:userID=2; __myapp:authenticationToken=xrSDsTZtUB-dbqsXFZYX; __myapp:userID=2; __myapp:authenticationToken=xrSDsTZtUB-dbqsXFZYX;"
```

**Comment by eXon** [comment]
Have you tried setting the path to / when saving and removing the cookie?

**Comment by jamesfzhang** [comment]
@eXon That appeared to have fixed the problem. Thank you.
