### ISSUE TITLE
Remove all cookies

### ISSUE THREAD

**Issue by javiermanzano** [eXon/react-cookie#19]
Maybe we can implement a **clearAll** method.

I can make a pull-request if you want.

**Comment by eXon** [comment]
I'm not sure this is a good practice to remove all cookies. If other tools (like Google Analytcs) use a cookie, you didn't only removed your own cookies but also all others.

**Comment by tadjohnston** [comment]
Might I suggest adding the ability to remove multiple cookies by array if that's what he's looking for.

**Comment by eXon** [comment]
I don't think this is needed.
