### ISSUE TITLE
JSON strignify stuff

### ISSUE THREAD

**Issue by hikkyu** [eXon/react-cookie#2]
Hello,

when I do `cookie.save('myCookie', 'test')`, I got this `%22test%22`.

What is the reason to do JSON.strignify even if val is a string ?

Thanks!

**Comment by eXon** [comment]
It makes sure that if you save a stringified object, it doesn't serialize it back,

Let's say you do: `cookie.save('myCookie', JSON.stringify({ test: true }))`

`cookie.get('myCookie')` will give you a string instead of an object.

**Comment by eXon** [comment]
This has been fixed in the last release. We no longer serialize string when saving them.

**Comment by hikkyu** [comment]
Thank's a lot!
