### ISSUE TITLE
Access server created cookies

### ISSUE THREAD

**Issue by florrain** [eXon/react-cookie#21]
Hi!

One issue I've been experiencing is that if I create a new cookie on the server side (express middleware), call `plugToRequest` before renderToString, the first render run on the server-side doesn't see the new cookie. 
If I refresh the page, it works correctly.

This makes sense since the plug is done on the request's cookies not the request's + the new ones in the Set-Cookie header
```js
function plugToRequest(req, res) {
  if (req.cookie) {
    _rawCookie = req.cookie;
  } else if (req.headers && req.headers.cookie) {
    setRawCookie(req.headers.cookie);
  } else {
    _rawCookie = {};
  }

  _res = res;
}
```

What do you suggest for that scenario so that both server and client can access the most up-to-date cookies or is a hard refresh really necessary?

Thanks.

**Comment by eXon** [comment]
How are you setting your new cookie? Are you setting it on the header of the res object?

**Comment by florrain** [comment]
I'm using express `res.cookie` like `res.cookie('cookie_name', 'cookie_val', { maxAge: 2592000000 });` and I believe this adds a value in the response header

**Comment by eXon** [comment]
Are you also setting the cookie on react-cookie server-side?

**Comment by arjunskumar47** [comment]
I'm also facing a similar issue in which I'm setting a cookie through express.
`res.cookie('cookie_name', 'cookie_val')`

and i'm unable to access it using cookie.load('cookie_name')

I'm not setting any cookie through react-cookie on the server or client.

**Comment by arjunskumar47** [comment]
@florrain This might be related - https://github.com/expressjs/session/issues/274

**Comment by eXon** [comment]
You should set the cookie using react-cookie (even server-side) otherwise their is no way to know it has been changed on the same request. Express doesn't really give us the infos.

**Comment by madhuripatil06** [comment]
same with me I am setting my cookie through django python set_cookie but not able to access it on react side
