### ISSUE TITLE
Different cookie for different request on server side?

### ISSUE THREAD

**Issue by gocreating** [eXon/react-cookie#23]
It seems that react-cookie's mechanism is manipulating the `_rawCookie` object. But for every request on server side, react-cookie uses the same `_rawCookie` object. I guess this might randomly cause error like below:

| timeline | user A | user B | _rawCookie |
| --- | --- | --- | --- |
| time 1 | save('token', tokenA) |  | { token: tokenA } |
| time 2 |  | save('token', tokenB) | { token: tokenB } |
| time 3 | res.end(...) |  | { token: tokenB } |
| time 4 |  | res.end(...) | { token: tokenB } |
| result | receive tokenB | receive tokenB |  |

Is my guessing possible?

**Comment by eXon** [comment]
You have to make sure you set the cookie values just before your renderToString (which is a sync operation). What you describe is not possible if you do so. Just make sure you're not doing anything async between.
