### ISSUE TITLE
maxAge requires milliseconds when using plugToRequest()

### ISSUE THREAD

**Issue by thomasstevens89** [eXon/react-cookie#27]
If you use reactCookie to save a cookie in node whilst using `plugToRequest` with express, then `maxAge` requires milliseconds, not seconds

From the express 4.x docs:

> ...Convenient option for setting the expiry time relative to the current time in milliseconds.

See: [http://expressjs.com/en/api.html#res.cookie](url)

I can submit a PR with the fix if you like.. let me know!

**Comment by kosz** [comment]
looks like that's how cookie does it also https://github.com/eXon/react-cookie/blob/master/index.js#L35

**Comment by eXon** [comment]
This is weird spec from Express. I wonder why they haven't kept the same as the official cookie specs.

**Comment by thomasstevens89** [comment]
Its probably because most express APIs use ms, not seconds (e.g. setting the maxAge for a cache-control header)

**Comment by eXon** [comment]
This will not be fixed. It is weird that express doesn't follow the convention but I don't think we should do a hack just for this library.
