### ISSUE TITLE
Cannot create httpOnly cookies

### ISSUE THREAD

**Issue by tention** [eXon/react-cookie#28]
Am using the following to create a httpOnly cookies. However the cookies is not created, Inspect mode in Chrome showing "The site has no cookies". The cookies should be visible with a tick on the HTTP column right? Cookies was created once I removed "httpOnly: true".

cookie.save('loginResult', user.token, { path: '/', httpOnly: true})

Any help would be appreciated. Thanks!

**Comment by eXon** [comment]
Where are you setting this? Is it in your Node.js code or in your client code?

**Comment by blitzd** [comment]
This appears to occur with cookie.load as well, I am not able to read a cookie that has been set with httpOnly: true. My cookie is set from a small Koa web app that is used for auth, if I disable httpOnly in that then the cookie.load from react-cookie will then work.

**Comment by eXon** [comment]
HTTP cookies are made to be only handled on the server. You cannot read them on the client. If you want to read them on the client, you have to use non-HTTP cookies.
