### ISSUE TITLE
Unable to remove cookie with domain

### ISSUE THREAD

**Issue by IljaDaderko** [eXon/react-cookie#30]
I set my cookies in 2 ways, note `cookie` comes from `var cookie = require('react-cookie')`

Cookie for localhost:
```
    cookie.save('sessionToken', '123')
```

Cookie for production
```
    cookie.save('sessionToken', '123, { domain: 'my.domain.io', secure: true })
```

These set cookies correctly, the only strange observation I can see is that in production case, cookies domain is set to `.my.domain.io` (has additional dot in front)

I then try to remove the cookie like so: `cookie.remove('sessionToken')` which works as expected on localhost, but doesn't get rid of the cookie on production.

**Comment by amalv** [comment]
I'm having a [similar problem](https://github.com/thereactivestack/react-cookie/issues/65).

How did you fix this?

**Comment by delveintechnolabs** [comment]
Having somewhat same problem.
When login i do `Cookie.save('my-cookie-name', {name: 'abx', email: 'abc@xyz.com'});`
When logout i do `Cookie.remove('my-cookie-name')`
(My app runs on localhost)
But doesnt work. 

Help Please...!!!!

**Comment by abhilash-linkites** [comment]
I am also facing the same issue. Does anyone find any solution?
