### ISSUE TITLE
cookie.load is giving me a different data from what I store in cookies

### ISSUE THREAD

**Issue by patrickpoh** [eXon/react-cookie#38]
hi! I am saving a user id of 1 in my cookies with the name id. However, on some occasions, the cookie.load('id') gave me a totally different value such as 3. I checked the cookie on my browser and it is clearly 1. Do you happen to know what is wrong?

**Comment by patrickpoh** [comment]
I went ahead and use cookie.load('id', true). Unfortunately, the same error happens.

**Comment by patrickpoh** [comment]
![cookieproblem](https://cloud.githubusercontent.com/assets/4413298/17960464/c83e9286-6ad8-11e6-9b32-c0aab5c8e5c6.PNG)

could it be it is returning me the size??

**Comment by eXon** [comment]
Do you have a way to reproduce? If I'm saving 1, I'm always loading 1 as well.

**Comment by patrickpoh** [comment]
Nope. It's purely random and all i did is cookie.load('id',true). So weird lol....

**Comment by eXon** [comment]
Have you tried with a different cookie name?

**Comment by patrickpoh** [comment]
nope! But i'll give it a try. I'll let you know if i face this issue again. Thank you

**Comment by gargsms** [comment]
This error will always happen if you try and save cookies from multiple pages in your application.
Cookies are always associated with a `path` and a `host`, so if you are saving multiple cookies with the same name from different pages, it is quite likely you are saving multiple cookies with each having different `path` (and maybe different `host` as well)

I handle this is by explicitly setting `path` and `host` while saving cookies. If I am working with, say, `http://www.example.com`, I would set my `host` to `.example.com` and `path` to `/`. This way the cookies are accessible on all subdomains and pages.

I am quite sure this will help your issue.
Not sure if there is some sort of global config you can use with this library.

**Comment by eXon** [comment]
I'm guessing this is solved. Let me know if it is not.
