### ISSUE TITLE
Cookies not working in Mozilla and Safari

### ISSUE THREAD

**Issue by sabapk** [eXon/react-cookie#43]
Cookies get destroyed when browser is closed. 
This is my code snippet. 

`const rssPageLoadCount = cookie.load('rssPageLoadCount-hash');
if (rssPageLoadCount) {
      if (rssPageLoadCount < 5) {
        cookie.save('rssPageLoadCount-hash', rssPageLoadCount + 1, {path: '/'});
      }
 } else {
      cookie.save(rssPageLoadCount-hash', 1, {path: '/'});
 }`

Until browser is open, the cookie behaviour works fine. Once I close and open browser again, and check in storage tab of developer console, I cannot find the cookie there

**Comment by sabapk** [comment]
I resolved this setting maxAge to a huge value.
`maxAge: 60 * 60 * 24 * 365 * 10`
By default, it seems to be setting the cookie value to session of user.

**Comment by eXon** [comment]
The default behavior of cookie is a session cookie. This means they are destroyed once the browser is closed.
