### ISSUE TITLE
Question: Cookie manipulation on the server

### ISSUE THREAD

**Issue by xpepermint** [eXon/react-cookie#5]
My isomorphic react app uses cookies to authenticate users. When a user tires to access a private route that requires authentication a loginReferrer cookie is set. This is not done when rendering on the server. As a workaround I `replace` the `cookie.save` method with the express method (res.cookie) on each request. Check the example below.

```js
// ExpressJS middleware for rendering react app on the server (react-router, alt, iso).

function render(req, res, next) {
  cookie.setRawCookie(req.headers.cookie);
  cookie.save = res.cookie;

  let location = new Location(req.path, req.query);
  Router.run(routes, location, (error, state, transition) => {
    if (error) return next(error);
    if (transition.isCancelled) return res.redirect(transition.redirectInfo.pathname);
    
    Alt.bootstrap({});
    let markup = ReactDomServer.renderToString(<Router {...state}/>);
    let html = Iso.render(markup, Alt.flush());
    res.render('index', {html});
  });
}
```

I'm posting this question to see if others have a better solution to this problem. Maybe we could add a method that would patch the library on every request similar to the above.

```js
// example ...
function render(req, res, next) {
  cookie.patchHandler(req);
  ...
}
```

**Comment by eXon** [comment]
In the last version, you can use plugToRequest :)

```javascript
function render(req, res, next) {
  cookie.plugToRequest(req, res);

  let location = new Location(req.path, req.query);
  Router.run(routes, location, (error, state, transition) => {
    if (error) return next(error);
    if (transition.isCancelled) return res.redirect(transition.redirectInfo.pathname);

    Alt.bootstrap({});
    let markup = ReactDomServer.renderToString(<Router {...state}/>);
    let html = Iso.render(markup, Alt.flush());
    res.render('index', {html});
  });
}
```

**Comment by xpepermint** [comment]
thx :)

**Comment by xpepermint** [comment]
@eXon Thanks, but this doesn't mean you can manipulate cookies. Can we add this also?

**Comment by eXon** [comment]
Notice that plugToRequest takes two parameters: req and res. It is completely isomorphic cookies, the changes will be sent to the client :)

**Comment by xpepermint** [comment]
Ow... I see... good then ;).
