### ISSUE TITLE
maxAge does not work

### ISSUE THREAD

**Issue by varunshah1106** [eXon/react-cookie#7]
When I am trying to set the maxAge of the cookie, it does not work. Instead, the cookie expiry is set to session. This is how I am doing it:
`cookie.save('Tachyon-API-Token', response.token, maxAge='3600', path='/');`

**Comment by varunshah1106** [comment]
I also tried an integer, so
`cookie.save('Tachyon-API-Token', response.token, maxAge=3600, path='/');`
does not work either.

**Comment by eXon** [comment]
Have you tried:
`cookie.save('Tachyon-API-Token', response.token, { maxAge: 3600, path='/' });`

**Comment by varunshah1106** [comment]
Yes. I tried that too, on Chrome as well as FireFox and it does not work.

**Comment by varunshah1106** [comment]
Worked!

**Comment by eXon** [comment]
No this is working as designed

**Comment by JuoCode** [comment]
@eXon **{ maxAge: 3600, path='/' }**`  
There is something wrong with the grammar
