### ISSUE TITLE
Somehow an cookie is kept in memory with webpack.

### ISSUE THREAD

**Issue by lemonCMS** [eXon/react-cookie#9]
I have an clientside / serverside setup.

When an user logs in an token cookie is set.
When i refresh the page to get all data fresh from the servers, this works correctly,

After logout and thus removing the cookie, somehow the servercode still see's the cookie.

I can see clearly ion the request that no cookie is send. The only way right now for me to get it working correctly is as below

````javascript
  if (typeof(req.headers.cookie) !== 'undefined') {
    cookie.setRawCookie(req.headers.cookie);
  } else {
    //Force empty cookie
    cookie.setRawCookie('cookie:');
  }
````

I did not notice this behavior earlier on.
I am running 

nodejs - 4.1.2
webpack: 1.12.2
react: 0.14

**Comment by eXon** [comment]
This should be fixed in the last version.
